version: "2.3"

services:

  datagrid-service:
    build: .
    image: lreimer/datagrid-service:2.1
    mem_limit: 600m
    environment:
      - JAEGER_SERVICE_NAME=datagrid-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
    volumes:
      - ./src/main/hazelcast/hazelcast_default.xml:/opt/payara/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18080:8080"  # the HTTP endpoint
    networks:
      - jee7net

  jaeger:
    image: "jaegertracing/all-in-one:1.5.0"
    mem_limit: 256m
    expose:
      - "14268"
      - "9411"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
    ports:
      - "16686:16686"
    networks:
      - jee7net

networks:
  jee7net:
    driver: bridge
