version: "2.3"

services:
  message-queue:
    image: rmohr/activemq:5.14.3
    expose:
      - "61616"       # the JMS port
      - "1883"        # the MQTT port
      - "5672"        # the AMQP port
    ports:
      - "8161:8161"   # the admin web UI
    networks:
      - jee7net

  payment-service:
    build: .
    image: lreimer/payment-service:2.1
    mem_limit: 600m
    environment:
      - org_apache_deltaspike_ProjectStage=Development
      - JAEGER_SERVICE_NAME=payment-service
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
      - JAEGER_REPORTER_LOG_SPANS=true
    volumes:
      - ./src/main/hazelcast/hazelcast_default.xml:/payment-service/config/hazelcast.xml
    expose:
      - "5701"        # the outbound Hazelcast port
      - "54327"       # the multicast Hazelcast port
    ports:
      - "18083:8080"  # the HTTP endpoint
    depends_on:
      - message-queue
      - payment-db
    networks:
      - jee7net

  payment-db:
    image: "postgres:9.6.3"
    environment:
      - POSTGRES_USER=payment
      - POSTGRES_PASSWORD=12qwasyx
    ports:
      - "35432:5432"
    networks:
      - jee7net

  jaeger:
    image: "jaegertracing/all-in-one:1.5.0"
    mem_limit: 256m
    expose:
      - "14268"
      - "9411"
      - "5775/udp"
      - "6831/udp"
      - "6832/udp"
      - "5778"
    ports:
      - "16686:16686"
    networks:
      - jee7net

networks:
  jee7net:
    driver: bridge
