apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: process-service
  name: process-service
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: process-service
